In [4]:
!pip install numpy

In [6]:
import numpy as np

In [7]:
# Task 1.
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr2 = np.random.randint(1, 10, size=(3, 3))
arr2

array([[1, 8, 2],
       [7, 7, 5],
       [2, 3, 4]], dtype=int32)

In [9]:
# Task 2.
arr1.sum(), arr1.mean(), arr1.max()

(np.int64(55), np.float64(5.5), np.int64(10))

In [10]:
arr1 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
arr1[arr1 > 5] = 0
arr1

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])